name: Special README Publish

# use this for generating when you commit
# on:
#   push:
#     branches:
#       - master
# use this for testing scheduled (At every 5th minute.)
# on:
#   schedule:
#     - cron: "*/5 * * * *"
# use this for actual special readme repo (At minute 1 past every hour)
on:
  schedule:
    - cron: "1 */1 * * *""

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: npm install
    - run: npm start
    - run: git diff
    - run: |
          date > generated.txt
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "generated"
          git push

